version: '2'

#volumes:
#    db-data:

services:
    nginx:
        container_name: nginx
        image: mikeymike/learning-docker-nginx
        build:
            context: ./
            dockerfile: app.nginx.dockerfile
        working_dir: /var/www
        ports:
            - "80:80"

    php:
        container_name: php
        image: mikeymike/learning-docker-php
        build:
            context: ./
            dockerfile: app.php.dockerfile
        volumes:
            - "${HOME}/.composer:/root/.composer"
            - "${HOME}/.ssh:/root/.ssh"
        working_dir: /var/www
        ports:
            - 9000

#    db:
#        container_name: m2-docker-test-db
#        image: mysql:5.6
#        volumes:
#            - db-data
#            - "./.docker/db/:/docker-entrypoint-initdb.d/"
#        ports:
#            - "3306:3306"
#        restart: unless-stopped
#        env_file:
#            - ./.docker/production.env
