FROM nginx:latest
MAINTAINER Michael Woodward <michael@wearejh.com>

# Add project files, @see .dockerignore
# This only works with build from repo...
COPY pub /var/www/pub
COPY .docker/nginx/sites /etc/nginx/conf.d

# Shouldn't need volume
# VOLUME /var/www

CMD ["nginx", "-g", "daemon off;"]