version: '2'

volumes:
    db-data:

services:
    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: dockerfile.web
        working_dir: /var/www
        ports:
            - "80:80"
        env_file:
            - ./.docker/production.env

    php:
        container_name: php
        build:
            context: ./
            dockerfile: dockerfile.app
        volumes:
            - "${HOME}/.composer:/root/.composer"
            - "${HOME}/.ssh:/root/.ssh"
        working_dir: /var/www
        ports:
            - 9000
        env_file:
            - ./.docker/production.env

#    db:
#        container_name: m2-docker-test-db
#        image: mysql:5.6
#        volumes:
#            - db-data
#            - "./.docker/db/:/docker-entrypoint-initdb.d/"
#        ports:
#            - "3306:3306"
#        restart: unless-stopped
#        env_file:
#            - ./.docker/production.env
